version: '3'

services:
  db:
    # MacOS m1칩 사용자들은 아래 주석을 해제하고 실행해주세요
    # platform: linux/x86_64
    volumes:
      - ./db/data:/var/lib/mysql
    build:
      context: ./db
      dockerfile: dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: Chilsu
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./backend:/usr/src/app
    restart: always
  # frontend:
  #   depends_on:
  #     - backend
  #   build:
  #     context: ./frontend
  #     dockerfile: dockerfile.dev
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend:/usr/src/app

